repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: "\\.idea/(.)*"
      - id: trailing-whitespace
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.34.0
    hooks:
      - id: pyupgrade
        args: ["--py37-plus"]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: [--config=./pyproject.toml]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
      - id: prettier
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        exclude: "test_*"
        args: ["-iii", "-ll", "-s=B308,B703"]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          [
            "flake8-bugbear",
            "flake8-comprehensions",
            "flake8-mutable",
            "flake8-print",
            "flake8-simplify",
            "flake8-type-checking",
          ]
  - repo: https://github.com/ariebovenberg/slotscheck
    rev: v0.14.1
    hooks:
      - id: slotscheck
        exclude: "^(?!starlite/)"
        additional_dependencies:
          [
            openapi_schema_pydantic,
            orjson,
            pydantic,
            pydantic_factories,
            pyyaml,
            starlette,
            sqlalchemy,
            requests,
            jinja2,
            mako,
          ]
  - repo: https://github.com/pycqa/pylint
    rev: "v2.14.4"
    hooks:
      - id: pylint
        exclude: "test_*"
        args: ["--unsafe-load-any-extension=y"]
        additional_dependencies:
          [
            mkdocs_gen_files,
            openapi_schema_pydantic,
            orjson,
            pydantic,
            pydantic_factories,
            pyyaml,
            starlette,
            sqlalchemy,
          ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.961"
    hooks:
      - id: mypy
        additional_dependencies:
          [
            orjson,
            types-PyYAML,
            types-requests,
            openapi_schema_pydantic,
            pydantic,
            pydantic_factories,
            starlette,
            sqlalchemy,
            types-freezegun,
          ]
