site_name: Starlite
repo_url: https://github.com/starlite-api/starlite
repo_name: starlite-api/starlite
site_url: https://starlite-api.github.io/starlite
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: mirage
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: mirage-light
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  favicon: images/starlite-favicon.ico
  logo: images/2x/starlite-icon@2x.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tracking
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
  plugins:
    - search
    - social:
        cards_color:
          fill: "#1d2433"
          text: "#d6dbe1"
        cards_font: Tahoma
extra_css:
  - css/extra.css
nav:
  - Overview: index.md
  - Usage:
      - usage/0-the-starlite-app.md
      - usage/1-routers-and-controllers.md
      - Route Handlers:
          - usage/2-route-handlers/0_route_handlers_concept.md
          - usage/2-route-handlers/1_http_route_handlers.md
          - usage/2-route-handlers/2_websocket_route_handlers.md
          - usage/2-route-handlers/3_asgi_route_handlers.md
      - usage/3-parameters.md
      - usage/4-request-body.md
      - usage/5-responses.md
      - usage/6-dependency-injection.md
      - usage/7-middleware.md
      - usage/8-authentication.md
      - usage/9-guards.md
      - usage/10-plugins.md
      - usage/11-data-transfer-objects.md
      - usage/12-openapi.md
      - usage/13-request-lifecycle-hooks.md
      - usage/14-testing.md
      - usage/15-templating.md
      - usage/16-caching.md
      - usage/17-exceptions.md
  - API:
      - api.md
  - migration.md
  - governance-and-contribution.md
  - license.md
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/X3FJqy8d2j
    - icon: fontawesome/brands/github
      link: https://github.com/starlite-api/starlite
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            heading_level: 3
            show_root_heading: true
            show_source: false
watch:
  - starlite
